### ISSUE TITLE
Стрелял

### ISSUE THREAD

**Issue by geravod** [LolaperezDS/BlockWars2#5]
пытался найти кнопку стрельбы и тыкал на ЛКМ, а потом на ПКМ на пушке. Вскоре, когда я вспомнил, что это ПКМ, я решил на пушке стрельнуть на здании которое находится на правом углу квадрата на 1 клетки от пушки. После чего игра перестала отвечать и мне пришлось использовать горячие клавиши alt+f4. Пожалуйста решите эту проблему!

**Comment by LolaperezDS** [comment]
ОК, посмотрю)

**Comment by LolaperezDS** [comment]
Решено)
